version: '3'
services:
  postgres:
    image: 'postgres:latest'
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: wertyta13
      POSTGRES_USER: postgres
      POSTGRES_DB: skt_task_v
    volumes:  
      - "./sql/init.sql:/docker-entrypoint-initdb.d/init.sql"
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
