spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

product:
  rabbitmq:
    insertExchange: product-exchange
    insertQueue: insertProduct-queue
    insertRoutingkey: insertRoutingkey
    getProductsExchange: getProductsExchange
    getProductsQueue: getProductsQueue
    getProductsRoutingkey: getProductsRoutingkey
    getProductsMessage: getProducts

server:
  port: 3000
