spring:
  datasource:
    url: jdbc:postgresql://localhost/skt_task
    username: postgres
    password: wertyta13

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    generate-ddl: true

    properties:
      hibernate:
        default_schema: public
        format_sql: true
        temp.use_jdbc_metadata_defaults: false